version: "3.9"
services:
  api:
    build: ./code/deployment/api
    container_name: mnist_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
  app:
    build: ./code/deployment/app
    container_name: mnist_app
    ports:
      - "8501:8501"
    depends_on:
      - api
